package com.italianswapp.yourtraining.WorkoutProposed.WorkoutProposed;

import com.italianswapp.yourtraining.Timer.Circuit.CircuitSettings.Exercise;
import com.italianswapp.yourtraining.Timer.Circuit.CircuitSettings.ExerciseBuilder;
import com.italianswapp.yourtraining.WorkoutProposed.Workout.Workout;
import com.italianswapp.yourtraining.WorkoutProposed.Workout.WorkoutBuilder;

public class BodybuildingWorkoutProposed extends ProposedWorkoutList  {

    public BodybuildingWorkoutProposed() {
        super();
        initializeWorkoutList();
    }

    private void initializeWorkoutList() {

        /*
        Panca piana 4x5
        Push ups 2x30
        5 Military press + 8 panca inclinata x 3
        5 dips + 8 alzate laterali + 3
        2x15 dips
        5 panca stretta + 8 french press x 3
         */

        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Push superset hypertrophy")
                        .setCategory(Workout.WorkoutCategory.BODYBUILDING)
                        .setPremium()
                        .setLevel(Workout.WorkoutLevel.ADVANCED)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Bench press")
                                .setReps(5)
                                .setRepetition(4)
                                .setRec(minToMills(2))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Push ups")
                                .setReps(30)
                                .setRepetition(2)
                                .setRec(minToMills(2))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("Military press")
                                .setReps(5)
                                .setRepetition(3)
                                .setRec(secToMills(90))
                                .setIsReps(true)
                                .setSupersetExercise(8, true, "Incline bench press")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("Dips")
                                .setReps(5)
                                .setRepetition(3)
                                .setRec(secToMills(90))
                                .setIsReps(true)
                                .setSupersetExercise(8, true, "Side raises")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Dips")
                                .setReps(15)
                                .setRepetition(2)
                                .setRec(minToMills(2))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("Bench press tight grip")
                                .setReps(5)
                                .setRepetition(3)
                                .setRec(secToMills(90))
                                .setIsReps(true)
                                .setSupersetExercise(8, true, "French press")
                                .build())
                        .build()
        );

        /*
        Lat 4x5
        Chin up 2x30
        5 Rematore + 8 Pull over x 3
        5 Trazioni + 8 Scrollate + 3
        Chin ups 2x15
        5 hammer + 8 curl bilanciere x 3
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                .setTitle("Pull superset hypertrophy")
                .setCategory(Workout.WorkoutCategory.BODYBUILDING)
                .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                .setPremium()
                .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                .addMuscleGroup(Workout.MuscleGroup.BICEPS)
                .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                .addExercise(ExerciseBuilder.newBuilder()
                        .setType(Exercise.CircuitType.EXERCISE)
                        .setName("Lat machine")
                        .setReps(5)
                        .setRepetition(4)
                        .setRec(minToMills(2))
                        .setIsReps(true)
                        .build())
                .addExercise(ExerciseBuilder.newBuilder()
                        .setType(Exercise.CircuitType.EXERCISE)
                        .setName("Chin ups")
                        .setReps(15)
                        .setRepetition(2)
                        .setRec(minToMills(2))
                        .setIsReps(true)
                        .build())
                .addExercise(ExerciseBuilder.newBuilder()
                        .setType(Exercise.CircuitType.SUPERSET)
                        .setName("Bent over row")
                        .setReps(5)
                        .setRepetition(3)
                        .setRec(secToMills(90))
                        .setIsReps(true)
                        .setSupersetExercise(8, true, "Pull over")
                        .build())
                .addExercise(ExerciseBuilder.newBuilder()
                        .setType(Exercise.CircuitType.SUPERSET)
                        .setName("Pull ups")
                        .setReps(5)
                        .setRepetition(3)
                        .setRec(secToMills(90))
                        .setIsReps(true)
                        .setSupersetExercise(8, true, "Shrugs")
                        .build())
               .addExercise(ExerciseBuilder.newBuilder()
                        .setType(Exercise.CircuitType.EXERCISE)
                        .setName("Reverse pull ups")
                        .setReps(15)
                        .setRepetition(2)
                        .setRec(minToMills(2))
                        .setIsReps(true)
                        .build())
                .addExercise(ExerciseBuilder.newBuilder()
                        .setType(Exercise.CircuitType.SUPERSET)
                        .setName("Curl hammer")
                        .setReps(5)
                        .setRepetition(3)
                        .setRec(secToMills(90))
                        .setIsReps(true)
                        .setSupersetExercise(8, true, "Barbell curl")
                        .build())
                .build()
        );

         /*
        Squats 4x5
        Squat jump 2x30
        5 Deadlift + 8 Lounges x 3
        5 Affondi + 8 Leg extension + 3
        Calf 2x30
        12 Crunch + 12 Leg raises x 3
        plank 3x45"
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Leg superset hypertrophy")
                        .setCategory(Workout.WorkoutCategory.BODYBUILDING)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .setPremium()
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.CALVES)
                        .addMuscleGroup(Workout.MuscleGroup.FEMORAL_BICEPS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Squats")
                                .setReps(5)
                                .setRepetition(4)
                                .setRec(minToMills(2))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Squat jump")
                                .setReps(15)
                                .setRepetition(2)
                                .setRec(minToMills(2))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("Deadlift")
                                .setReps(5)
                                .setRepetition(3)
                                .setRec(secToMills(90))
                                .setIsReps(true)
                                .setSupersetExercise(8, true, "Lounges")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("Lounges")
                                .setReps(5)
                                .setRepetition(3)
                                .setRec(secToMills(90))
                                .setIsReps(true)
                                .setSupersetExercise(8, true, "Leg extension")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Calf raises")
                                .setReps(30)
                                .setRepetition(2)
                                .setRec(minToMills(2))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("Crunch")
                                .setReps(15)
                                .setRepetition(3)
                                .setRec(secToMills(90))
                                .setIsReps(true)
                                .setSupersetExercise(15, true, "Leg raises")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Plank")
                                .setReps((int) secToMills(45))
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(false)
                                .build())
                        .build()
        );

        /*
        Panca piana 3x3
        Military press 5x5
        Spinte panca inclinata 3x10
        Alzate laterali 3x10
        Dip zavorrati 3x10
        French Press 3x10
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Push for strength")
                        .setCategory(Workout.WorkoutCategory.BODYBUILDING)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Flat bench")
                                .setReps(3)
                                .setRepetition(3)
                                .setRec(secToMills(120))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Military press")
                                .setReps(5)
                                .setRepetition(5)
                                .setRec(secToMills(90))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("inclined bench press")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("lateral raises")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Dips")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("French press")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        Stacco 3x3
        Trazioni zavorrate 5x5
        Pull Over 3x10
        Rematore 3x10
        Curl Ez 3x10
        Curl Manubri 3x10
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Pull for strength")
                        .setCategory(Workout.WorkoutCategory.BODYBUILDING)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .setPremium()
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.LUMBAR)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Deadlifts")
                                .setReps(3)
                                .setRepetition(3)
                                .setRec(secToMills(120))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Pull ups")
                                .setReps(5)
                                .setRepetition(5)
                                .setRec(secToMills(90))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Pull over")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Bent over row")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Curl Ez")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Dumbbells curl")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        Squat 3x3
        Stacco 5x5
        Affondi 3x10
        Hip Trust 3x15
        Leg Curl 3x10
        Leg Culf 3x25
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Legs for strenght")
                        .setCategory(Workout.WorkoutCategory.BODYBUILDING)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.FEMORAL_BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.LUMBAR)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Squat")
                                .setReps(3)
                                .setRepetition(3)
                                .setRec(secToMills(120))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Deadlift")
                                .setReps(5)
                                .setRepetition(5)
                                .setRec(secToMills(90))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Lunges")
                                .setReps(2)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Hip trust")
                                .setReps(15)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Leg curl")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Leg calf")
                                .setReps(25)
                                .setRepetition(3)
                                .setRec(secToMills(45))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        Panca piana 3x12
        Stacco 3x12
        Military press 3x12
        Affondi 3x20
        Rematore 3x12
        Curl 3x12
        Plank 3x40"
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Adaptation for multifrequency 1")
                        .setCategory(Workout.WorkoutCategory.BODYBUILDING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.LUMBAR)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Bench press")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(75))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Deadlift")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(75))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Military press")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(75))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Back lounge")
                                .setReps(20)
                                .setRepetition(3)
                                .setRec(secToMills(75))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Bent over row")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(75))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Curl ez")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(75))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Plank")
                                .setReps((int) secToMills(40))
                                .setRepetition(3)
                                .setRec(secToMills(75))
                                .setIsReps(false)
                                .build())
                        .build()
        );

         /*
        Full squat 3x12
        Panca inclinata 3x12
        Trazioni inverse 3x12
        Stacchi rumeni 3x20
        Alzate laterali 3x12
        Dip parallele 3x12
        Sit ups 3x40"
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Adaptation for multifrequency 2")
                        .setCategory(Workout.WorkoutCategory.BODYBUILDING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.LUMBAR)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Full squat")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(75))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Incline bench press")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(75))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Reverse pull ups")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(75))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Stiff-legged deadlifts")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(75))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Lateral raises")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(75))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Dips")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(75))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Sit ups")
                                .setReps((int) secToMills(40))
                                .setRepetition(4)
                                .setRec(secToMills(75))
                                .setIsReps(false)
                                .build())
                        .build()
        );

        /*
        Pulley 3x12
        Panca piana 3x12
        Scollate bilanciere 3x12
        Panca stretta bilanciere 3x20
        Curl hammer 3x12
        Front squat 3x12
        Leg raises 3x40"
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Adaptation for multifrequency 3")
                        .setCategory(Workout.WorkoutCategory.BODYBUILDING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.LUMBAR)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Pulley")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(75))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Bench press")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(75))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Barbell shrugs")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(75))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Close grip bench press ")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(75))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Curl hammer")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(75))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Front squat")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(75))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Leg raises")
                                .setReps((int) secToMills(40))
                                .setRepetition(4)
                                .setRec(secToMills(75))
                                .setIsReps(false)
                                .build())
                        .build()
        );

        /*
        Alzate laterali 3x10
        Shoulder press 3x10
        Tirate al mento 3x10
        Riposo 2 minuti
        curl manubri 3x10
        Dip 3x10
        Tricipiti ai cavi 3x10
        Curl alla lat 3x10
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Arms to start")
                        .setCategory(Workout.WorkoutCategory.BODYBUILDING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .setPremium()
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Lateral raises")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Shoulder press")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Upright row")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.REST)
                                .setRec(secToMills(120))
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Dumbbells curl")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Dips")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Cable pushdown")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Lat Machine curl")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        Panca piana 3x15
        Croci 3x12
        Push ups 3x20
        Curl ex 3x12
        Curl manubri 3x12
        Plank 3x45"
        Crunch inverso 3x45"
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Repeated efforts 1")
                        .setCategory(Workout.WorkoutCategory.BODYBUILDING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Bench press")
                                .setReps(15)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Crossover")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Push ups")
                                .setReps(20)
                                .setRepetition(3)
                                .setRec(secToMills(90))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Curl ez")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Dumbbells curl")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Plank")
                                .setReps((int) secToMills(45))
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Reverse crunch")
                                .setReps((int) secToMills(45))
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(false)
                                .build())
                        .build()
        );

        /*
        Rematore 3x15
        Lat 3x12
        Trazioni orizzontali 3x20
        Scrollate 3x12
        French press 3x12
        Dip 3x10
        Sit ups 3x45"
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Repeated efforts 2")
                        .setCategory(Workout.WorkoutCategory.BODYBUILDING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Bent over row")
                                .setReps(15)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Lat machine")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Australian pull ups")
                                .setReps(20)
                                .setRepetition(3)
                                .setRec(secToMills(90))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Shrugs")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("French press")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Dips")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(90))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Sit up")
                                .setReps((int) secToMills(45))
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(false)
                                .build())
                        .build()
        );

        /*
        Panca piana 3x15
        Croci 3x12
        Push ups 3x20
        Curl ex 3x12
        Curl manubri 3x12
        Plank 3x45"
        Crunch inverso 3x45"
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Repeated efforts 3")
                        .setCategory(Workout.WorkoutCategory.BODYBUILDING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.FEMORAL_BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.CALVES)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Barbell squats")
                                .setReps(15)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Deadlifts")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Squat jump")
                                .setReps(20)
                                .setRepetition(3)
                                .setRec(secToMills(90))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Calf raises")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Military press")
                                .setReps(15)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Lateral raises")
                                .setReps(20)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Front raises")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        Miletto spinta full body mese 3
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Full body push")
                        .setCategory(Workout.WorkoutCategory.BODYBUILDING)
                        .setLevel(Workout.WorkoutLevel.ADVANCED)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Bench press")
                                .setReps(3)
                                .setRepetition(3)
                                .setRec(secToMills(210))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Military press")
                                .setReps(8)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("French press")
                                .setReps(8)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EMOM)
                                .setName("Push ups")
                                .setReps( (int) secToMills(60))
                                .setRepetition(10)
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Barbell squats")
                                .setReps(3)
                                .setRepetition(3)
                                .setRec(secToMills(210))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Leg extensions")
                                .setReps(8)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EMOM)
                                .setName("Squat jump")
                                .setReps( (int) secToMills(60))
                                .setRepetition(10)
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Crunch")
                                .setReps(20)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        Miletto tirata full body mese 3
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Full body pull")
                        .setCategory(Workout.WorkoutCategory.BODYBUILDING)
                        .setLevel(Workout.WorkoutLevel.ADVANCED)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.FEMORAL_BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Pull ups")
                                .setReps(3)
                                .setRepetition(3)
                                .setRec(secToMills(210))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Pulley machine")
                                .setReps(8)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Shrug")
                                .setReps(8)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EMOM)
                                .setName("Dumbbells curl")
                                .setReps( (int) secToMills(60))
                                .setRepetition(10)
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Deadlifts")
                                .setReps(3)
                                .setRepetition(3)
                                .setRec(secToMills(210))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Good morning")
                                .setReps(8)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EMOM)
                                .setName("Leg curl")
                                .setReps( (int) secToMills(60))
                                .setRepetition(10)
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Sit ups")
                                .setReps(20)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        Miletto spinta 2 mese 3
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Full body push strength")
                        .setCategory(Workout.WorkoutCategory.BODYBUILDING)
                        .setLevel(Workout.WorkoutLevel.ADVANCED)
                        .setPremium()
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.CALVES)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Bench press")
                                .setReps(5)
                                .setRepetition(3)
                                .setRec(secToMills(120))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Crossover")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Lateral raises")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EMOM)
                                .setName("Dips")
                                .setReps( (int) secToMills(60))
                                .setRepetition(12)
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Front squats")
                                .setReps(5)
                                .setRepetition(3)
                                .setRec(secToMills(120))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Lounges")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EMOM)
                                .setName("Calf raises")
                                .setReps( (int) secToMills(60))
                                .setRepetition(12)
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Plank")
                                .setReps(((int) secToMills(60)))
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(false)
                                .build())
                        .build()
        );

        /*
        Miletto tirata 2 mese 3
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Full body pull strength")
                        .setCategory(Workout.WorkoutCategory.BODYBUILDING)
                        .setLevel(Workout.WorkoutLevel.ADVANCED)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.FEMORAL_BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Chin ups")
                                .setReps(5)
                                .setRepetition(3)
                                .setRec(secToMills(120))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Bent over row")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Dumbbells curl")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EMOM)
                                .setName("Curl ez")
                                .setReps( (int) secToMills(60))
                                .setRepetition(12)
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Deadlifts")
                                .setReps(5)
                                .setRepetition(3)
                                .setRec(secToMills(120))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EMOM)
                                .setName("Leg curl")
                                .setReps( (int) secToMills(60))
                                .setRepetition(12)
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Reverse crunch")
                                .setReps(15)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Hollow body")
                                .setReps(((int) secToMills(60)))
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(false)
                                .build())
                        .build()
        );

        /*
        Allenamento per donne
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Women workout")
                        .setCategory(Workout.WorkoutCategory.BODYBUILDING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.FEMORAL_BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Barbell hip bridge")
                                .setReps(20)
                                .setRepetition(2)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Deadbug")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Louge")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.REST)
                                .setRec(secToMills(120))
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Renegade row")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Romanian deadlift")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Floor press")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Russian twist")
                                .setReps((int) secToMills(30))
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(false)
                                .build())
                        .build()
        );

        /*
        Allenamento per donne petto e braccia
         */
        workoutList.add(
            WorkoutBuilder.newBuilder()
                    .setTitle("Arms for women")
                    .setCategory(Workout.WorkoutCategory.BODYBUILDING)
                    .setLevel(Workout.WorkoutLevel.BEGINNER)
                    .addMuscleGroup(Workout.MuscleGroup.CHEST)
                    .addMuscleGroup(Workout.MuscleGroup.BICEPS)
                    .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                    .addExercise(ExerciseBuilder.newBuilder()
                            .setType(Exercise.CircuitType.EXERCISE)
                            .setName("Flat bench press")
                            .setReps(8)
                            .setRepetition(4)
                            .setRec(secToMills(60))
                            .setIsReps(true)
                            .build())
                    .addExercise(ExerciseBuilder.newBuilder()
                            .setType(Exercise.CircuitType.EXERCISE)
                            .setName("Push ups")
                            .setReps(10)
                            .setRepetition(4)
                            .setRec(secToMills(60))
                            .setIsReps(true)
                            .build())
                    .addExercise(ExerciseBuilder.newBuilder()
                            .setType(Exercise.CircuitType.EXERCISE)
                            .setName("Cable crossover")
                            .setReps(15)
                            .setRepetition(3)
                            .setRec(secToMills(60))
                            .setIsReps(true)
                            .build())
                    .addExercise(ExerciseBuilder.newBuilder()
                            .setType(Exercise.CircuitType.EXERCISE)
                            .setName("Incline flyes")
                            .setReps(12)
                            .setRepetition(4)
                            .setRec(secToMills(60))
                            .setIsReps(true)
                            .build())
                    .addExercise(ExerciseBuilder.newBuilder()
                            .setType(Exercise.CircuitType.REST)
                            .setRec(secToMills(120))
                            .build())
                    .addExercise(ExerciseBuilder.newBuilder()
                            .setType(Exercise.CircuitType.EXERCISE)
                            .setName("Babrell curl")
                            .setReps(15)
                            .setRepetition(3)
                            .setRec(secToMills(60))
                            .setIsReps(true)
                            .build())
                    .addExercise(ExerciseBuilder.newBuilder()
                            .setType(Exercise.CircuitType.EXERCISE)
                            .setName("Curl hammer")
                            .setReps(12)
                            .setRepetition(4)
                            .setRec(secToMills(60))
                            .setIsReps(true)
                            .build())
                    .addExercise(ExerciseBuilder.newBuilder()
                            .setType(Exercise.CircuitType.EXERCISE)
                            .setName("Triceps rope extension")
                            .setReps(20)
                            .setRepetition(3)
                            .setRec(secToMills(60))
                            .setIsReps(true)
                            .build())
                    .addExercise(ExerciseBuilder.newBuilder()
                            .setType(Exercise.CircuitType.REST)
                            .setRec(secToMills(120))
                            .build())
                    .addExercise(ExerciseBuilder.newBuilder()
                            .setType(Exercise.CircuitType.EXERCISE)
                            .setName("Elliptical machine")
                            .setReps((int) minToMills(10))
                            .setRepetition(1)
                            .setRec(secToMills(60))
                            .setIsReps(false)
                            .build())
                    .build()
        );

        /*
        Allenamento per donne spalle e schiena
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Shoulders and back for women")
                        .setCategory(Workout.WorkoutCategory.BODYBUILDING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .setPremium()
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Military press")
                                .setReps(10)
                                .setRepetition(4)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Lateral raises")
                                .setReps(15)
                                .setRepetition(4)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Shoulder press")
                                .setReps(10)
                                .setRepetition(4)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Dumbbell shrugs")
                                .setReps(10)
                                .setRepetition(4)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Close-grip lat pulldowns")
                                .setReps(12)
                                .setRepetition(4)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.REST)
                                .setRec(secToMills(120))
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("T-bar rows")
                                .setReps(10)
                                .setRepetition(4)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Stationary bike")
                                .setReps((int) minToMills(10))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .build()
        );

        /*
        Gambe per donne
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Leg for women")
                        .setCategory(Workout.WorkoutCategory.BODYBUILDING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.CALVES)
                        .addMuscleGroup(Workout.MuscleGroup.FEMORAL_BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Barbell squats")
                                .setReps(8)
                                .setRepetition(4)
                                .setRec(secToMills(90))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Leg press machine")
                                .setReps(12)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Leg extensions")
                                .setReps(15)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Hamstring curls")
                                .setReps(15)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Lounges")
                                .setReps(10)
                                .setRepetition(4)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Calf raises")
                                .setReps(20)
                                .setRepetition(4)
                                .setRec(secToMills(45))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.REST)
                                .setRec(secToMills(120))
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Elliptical machine")
                                .setReps((int) minToMills(10))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .build()

        );
    }


}
