package com.italianswapp.yourtraining.WorkoutProposed.WorkoutProposed;

import com.italianswapp.yourtraining.Timer.Circuit.CircuitSettings.Exercise;
import com.italianswapp.yourtraining.Timer.Circuit.CircuitSettings.ExerciseBuilder;
import com.italianswapp.yourtraining.WorkoutProposed.Workout.Workout;
import com.italianswapp.yourtraining.WorkoutProposed.Workout.WorkoutBuilder;

public class FreeBodyWorkoutProposed extends  ProposedWorkoutList {

    public FreeBodyWorkoutProposed() {
        super();
        initializeWorkoutList();
    }

    private void initializeWorkoutList() {
        /*
        100 reps
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("AFAP 100 reps full body")
                        .setCategory(Workout.WorkoutCategory.BODYBUILDING)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Lat machine")
                                .setReps(100)
                                .setRepetition(1)
                                .setRec(0)
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Bench press")
                                .setReps(100)
                                .setRepetition(1)
                                .setRec(0)
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Hack squats")
                                .setReps(100)
                                .setRepetition(1)
                                .setRec(0)
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Sit ups")
                                .setReps(100)
                                .setRepetition(1)
                                .setRec(0)
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        Circuito donne principianti
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Bodyweight circuit for women")
                        .setCategory(Workout.WorkoutCategory.FREEBODY)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .setPremium()
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Squats")
                                .setReps(16)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Push ups")
                                .setReps(4)
                                .setRepetition(10)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Chin ups")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Glute kick Back")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .setSupersetExercise(10, true, "Lunges")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Tricep bench dip")
                                .setReps(10)
                                .setRepetition(5)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        Circuito donne avanzato
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Bodyweight advanced for women")
                        .setCategory(Workout.WorkoutCategory.FREEBODY)
                        .setLevel(Workout.WorkoutLevel.ADVANCED)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Squats jump")
                                .setReps(16)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("1 Leg Push ups")
                                .setReps(4)
                                .setRepetition(10)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Pull ups")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Frog pumps")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .setSupersetExercise(10, true, "Jumping Lunges")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Burpees")
                                .setReps(10)
                                .setRepetition(5)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        Allenamento base per uomini parte alta
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Build muscle")
                        .setCategory(Workout.WorkoutCategory.FREEBODY)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BICEPS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Push ups")
                                .setReps(15)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Pull ups")
                                .setReps(3)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Jackknife push ups")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Diamond push ups")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Inverted biceps curl")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        Allenamento base per uomini parte bassa
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Build muscle")
                        .setCategory(Workout.WorkoutCategory.FREEBODY)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .setPremium()
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.FEMORAL_BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.CALVES)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Calf raises")
                                .setReps(15)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Jump squat")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Walkin lunge")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Hanging leg raise")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        Giorno 1 aica
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Fight against time")
                        .setCategory(Workout.WorkoutCategory.FREEBODY)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Push ups")
                                .setReps(((int) secToMills(20)))
                                .setRepetition(10)
                                .setRec(secToMills(30))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Iso chin up")
                                .setReps(((int) secToMills(10)))
                                .setRepetition(10)
                                .setRec(secToMills(30))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Crunch")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(5)
                                .setRec(secToMills(30))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Plank")
                                .setReps(((int) secToMills(45)))
                                .setRepetition(5)
                                .setRec(secToMills(45))
                                .setIsReps(false)
                                .build())
                        .build()
        );

        /*
        Allenamento gambe
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Legs on fire")
                        .setCategory(Workout.WorkoutCategory.FREEBODY)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.CARDIO)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Jumping lounges")
                                .setReps(20)
                                .setRepetition(4)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .setSupersetExercise(200, true, "200mt Sprint")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Box squat")
                                .setReps(20)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.REST)
                                .setRec(secToMills(120))
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Burpees")
                                .setReps(20)
                                .setRepetition(5)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        Challenge 200 burpees
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Burpees challenge")
                        .setCategory(Workout.WorkoutCategory.FREEBODY)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.CARDIO)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addMuscleGroup(Workout.MuscleGroup.CALVES)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Burpees")
                                .setReps(200)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        Programma GOI
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Military training")
                        .setCategory(Workout.WorkoutCategory.FREEBODY)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Reverse crunch")
                                .setReps(20)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Dip crunch")
                                .setReps(15)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Crunch")
                                .setReps(20)
                                .setRepetition(4)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Dip")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(45))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Push ups")
                                .setReps(25)
                                .setRepetition(3)
                                .setRec(secToMills(45))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Push up legs elevated")
                                .setReps(20)
                                .setRepetition(2)
                                .setRec(secToMills(45))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Pull ups")
                                .setReps(5)
                                .setRepetition(3)
                                .setRec(secToMills(40))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Australian pull ups")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(35))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Chin ups")
                                .setReps(10)
                                .setRepetition(1)
                                .setRec(secToMills(30))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Diamond push ups")
                                .setReps(15)
                                .setRepetition(1)
                                .setRec(secToMills(25))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("V push ups")
                                .setReps(10)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        Allenamento cardio principianti
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Home cadio")
                        .setCategory(Workout.WorkoutCategory.FREEBODY)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .setPremium()
                        .addMuscleGroup(Workout.MuscleGroup.CARDIO)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.FEMORAL_BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.CALVES)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("SKip")
                                .setReps(((int) secToMills(45)))
                                .setRepetition(5)
                                .setRec(secToMills(30))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Sumo squat")
                                .setReps(10)
                                .setRepetition(4)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .setSupersetExercise(10, true, "Rotating lunges")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Jumping lunges")
                                .setReps(8)
                                .setRepetition(4)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Squat jump")
                                .setReps(10)
                                .setRepetition(5)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .build()
        );


        /*
        Fino a qui 10 allenamenti
         */

        /*
        Cardio a casa
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Lose weight")
                        .setCategory(Workout.WorkoutCategory.FREEBODY)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .addMuscleGroup(Workout.MuscleGroup.CARDIO)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Jumping rope")
                                .setReps(((int) secToMills(600)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.REST)
                                .setRec(secToMills(180))
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Step up")
                                .setReps(((int) secToMills(60)))
                                .setRepetition(3)
                                .setRec(secToMills(30))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("SKip")
                                .setReps(((int) secToMills(60)))
                                .setRepetition(3)
                                .setRec(secToMills(45))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Jumping jacks")
                                .setReps(20)
                                .setRepetition(3)
                                .setRec(secToMills(45))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Mountain climber")
                                .setReps(20)
                                .setRepetition(3)
                                .setRec(secToMills(45))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        Total body donne
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Total body for women")
                        .setCategory(Workout.WorkoutCategory.FREEBODY)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addMuscleGroup(Workout.MuscleGroup.CARDIO)
                        .addMuscleGroup(Workout.MuscleGroup.BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.LUMBAR)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Tapis roulant")
                                .setReps(((int) secToMills(600)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Crunch")
                                .setReps(20)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Jumping jacks")
                                .setReps(15)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .setSupersetExercise(20, true, "Biceps with elastic")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Tapis roulant")
                                .setReps(((int) secToMills(300)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Squats")
                                .setReps(10)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .setSupersetExercise(20, true, "French press")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Bridge")
                                .setReps(15)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Tapis roulant")
                                .setReps(((int) secToMills(300)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Lunges")
                                .setReps(10)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .setSupersetExercise(20, true, "Chest press")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Bent over row")
                                .setReps(15)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Tapis roulant")
                                .setReps(((int) secToMills(300)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .build()
        );

        /*
        Epic chest di darabee
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Epic chest")
                        .setCategory(Workout.WorkoutCategory.FREEBODY)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Push ups")
                                .setReps(25)
                                .setRepetition(3)
                                .setRec(secToMills(30))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Plank rotations")
                                .setReps(20)
                                .setRepetition(3)
                                .setRec(secToMills(30))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.REST)
                                .setRec(secToMills(120))
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Upward downward dog")
                                .setReps(25)
                                .setRepetition(3)
                                .setRec(secToMills(30))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Shoulder taps")
                                .setReps(20)
                                .setRepetition(3)
                                .setRec(secToMills(30))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        Wonder woman workout di darabee
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Wonder women workout")
                        .setCategory(Workout.WorkoutCategory.FREEBODY)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.LUMBAR)
                        .addMuscleGroup(Workout.MuscleGroup.FEMORAL_BICEPS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Leg swings")
                                .setReps(40)
                                .setRepetition(1)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Natural leg extension")
                                .setReps(40)
                                .setRepetition(1)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Side leg extensions")
                                .setReps(40)
                                .setRepetition(1)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.REST)
                                .setRec(secToMills(60))
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Downward upward dogs")
                                .setReps(4)
                                .setRepetition(1)
                                .setRec(secToMills(30))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Glutex flex")
                                .setReps(10)
                                .setRepetition(1)
                                .setRec(secToMills(45))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Scorpion twist")
                                .setReps(4)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        2 minuti di plank
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Two minute plank")
                        .setCategory(Workout.WorkoutCategory.FREEBODY)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Full plank")
                                .setReps(((int) secToMills(20)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Elbow plank")
                                .setReps(((int) secToMills(20)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Raised leg plank")
                                .setReps(((int) secToMills(20)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Side plank")
                                .setReps(((int) secToMills(20)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Full plank")
                                .setReps(((int) secToMills(20)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Elbow plank")
                                .setReps(((int) secToMills(20)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .build()
        );

        /*
        3 minuti di plank
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Three minute plank")
                        .setCategory(Workout.WorkoutCategory.FREEBODY)
                        .setLevel(Workout.WorkoutLevel.ADVANCED)
                        .setPremium()
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Full plank")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Elbow plank")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Raised leg plank")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Side plank")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Full plank")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Elbow plank")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .build()
        );

        /*
        4 minuti di plank
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Four minute plank")
                        .setCategory(Workout.WorkoutCategory.FREEBODY)
                        .setLevel(Workout.WorkoutLevel.ADVANCED)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Full plank")
                                .setReps(((int) secToMills(40)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Elbow plank")
                                .setReps(((int) secToMills(40)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Raised leg plank")
                                .setReps(((int) secToMills(40)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Side plank")
                                .setReps(((int) secToMills(40)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Full plank")
                                .setReps(((int) secToMills(40)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Elbow plank")
                                .setReps(((int) secToMills(40)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .build()
        );

        /*
        Allenamento isometria darabee
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Only hold")
                        .setCategory(Workout.WorkoutCategory.FREEBODY)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addMuscleGroup(Workout.MuscleGroup.LUMBAR)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Side leg raise hold")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Raised arms hold")
                                .setReps(((int) secToMills(60)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Squat hold")
                                .setReps(((int) secToMills(60)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Hollow hold")
                                .setReps(((int) secToMills(60)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Bridge hold")
                                .setReps(((int) secToMills(60)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .build()
        );

        /*
        Allenamento addominali avanzato
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Super abs")
                        .setCategory(Workout.WorkoutCategory.FREEBODY)
                        .setLevel(Workout.WorkoutLevel.ADVANCED)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Crunches")
                                .setReps(30)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Flutter kicks")
                                .setReps(20)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Bridges")
                                .setReps(20)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Crunches")
                                .setReps(30)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Leg raises")
                                .setReps(20)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Bridges")
                                .setReps(20)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Crunches")
                                .setReps(30)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Heel taps")
                                .setReps(20)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Bridges")
                                .setReps(20)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        Allenamento donne stop cellulite
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Stop cellulite")
                        .setCategory(Workout.WorkoutCategory.FREEBODY)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .setPremium()
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.FEMORAL_BICEPS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Wide squats")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(30))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Squat hold calf raises")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(30))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Back kicks")
                                .setReps(20)
                                .setRepetition(3)
                                .setRec(secToMills(30))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Leg extensions")
                                .setReps(20)
                                .setRepetition(3)
                                .setRec(secToMills(30))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Side leg extensions")
                                .setReps(20)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Glute flex")
                                .setReps(10)
                                .setRepetition(3)
                                .setRec(secToMills(30))
                                .setIsReps(true)
                                .build())
                        .build()
        );





    }
}
