package com.italianswapp.yourtraining.WorkoutProposed.WorkoutProposed;

import com.italianswapp.yourtraining.Timer.Circuit.CircuitSettings.Exercise;
import com.italianswapp.yourtraining.Timer.Circuit.CircuitSettings.ExerciseBuilder;
import com.italianswapp.yourtraining.WorkoutProposed.Workout.Workout;
import com.italianswapp.yourtraining.WorkoutProposed.Workout.WorkoutBuilder;

public class FunctionalTrainingWorkoutProposed extends ProposedWorkoutList {

    public FunctionalTrainingWorkoutProposed() {
        super();
        initializeWorkoutList();
    }

    private void initializeWorkoutList() {
        /*
        Crossfit per principianti
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("The best for beginners")
                        .setCategory(Workout.WorkoutCategory.FUNCTIONALTRAINING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .setPremium()
                        .addMuscleGroup(Workout.MuscleGroup.LUMBAR)
                        .addMuscleGroup(Workout.MuscleGroup.FEMORAL_BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.CARDIO)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Barbell deadlift")
                                .setReps(10)
                                .setRepetition(5)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Barbell squat")
                                .setReps(10)
                                .setRepetition(5)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Kettlebell swings")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(5)
                                .setRec(secToMills(60))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Box jumps")
                                .setReps(((int) secToMills(20)))
                                .setRepetition(5)
                                .setRec(secToMills(60))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.REST)
                                .setRec(secToMills(60))
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Treadmill sprints")
                                .setReps(((int) secToMills(60)))
                                .setRepetition(5)
                                .setRec(secToMills(60))
                                .setIsReps(false)
                                .build())
                        .build()
        );

        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Full body on fire")
                        .setCategory(Workout.WorkoutCategory.FUNCTIONALTRAINING)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("Thrusters")
                                .setReps(21)
                                .setRepetition(1)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .setSupersetExercise(9, true, "Pull ups")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.REST)
                                .setRec(secToMills(60))
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("Thrusters")
                                .setReps(15)
                                .setRepetition(1)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .setSupersetExercise(9, true, "Pull ups")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.REST)
                                .setRec(secToMills(60))
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("Thrusters")
                                .setReps(9)
                                .setRepetition(1)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .setSupersetExercise(9, true, "Pull ups")
                                .build())
                        .build()
        );

        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Helen")
                        .setCategory(Workout.WorkoutCategory.FUNCTIONALTRAINING)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .addMuscleGroup(Workout.MuscleGroup.CARDIO)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Run sprint")
                                .setReps(400)
                                .setRepetition(1)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("Swings")
                                .setReps(21)
                                .setRepetition(3)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .setSupersetExercise(12, true, "Pull ups")
                                .build())
                        .build()
        );

        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Cindy")
                        .setCategory(Workout.WorkoutCategory.FUNCTIONALTRAINING)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("Pull ups")
                                .setReps(5)
                                .setRepetition(5)
                                .setRec(secToMills(20))
                                .setIsReps(true)
                                .setSupersetExercise(10, true, "Press ups")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("Press ups")
                                .setReps(10)
                                .setRepetition(5)
                                .setRec(secToMills(20))
                                .setIsReps(true)
                                .setSupersetExercise(15, true, "Air squats")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("Pull ups")
                                .setReps(5)
                                .setRepetition(5)
                                .setRec(secToMills(20))
                                .setIsReps(true)
                                .setSupersetExercise(15, true, "Air squats")
                                .build())
                        .build()
        );

        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Annie")
                        .setCategory(Workout.WorkoutCategory.FUNCTIONALTRAINING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .setPremium()
                        .addMuscleGroup(Workout.MuscleGroup.CARDIO)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Double unders")
                                .setReps(50)
                                .setRepetition(1)
                                .setRec(secToMills(10))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Sit ups")
                                .setReps(50)
                                .setRepetition(1)
                                .setRec(secToMills(10))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Double unders")
                                .setReps(40)
                                .setRepetition(1)
                                .setRec(secToMills(10))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Sit ups")
                                .setReps(40)
                                .setRepetition(1)
                                .setRec(secToMills(10))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Double unders")
                                .setReps(30)
                                .setRepetition(1)
                                .setRec(secToMills(10))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Sit ups")
                                .setReps(30)
                                .setRepetition(1)
                                .setRec(secToMills(10))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Double unders")
                                .setReps(20)
                                .setRepetition(1)
                                .setRec(secToMills(10))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Sit ups")
                                .setReps(20)
                                .setRepetition(1)
                                .setRec(secToMills(10))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Double unders")
                                .setReps(10)
                                .setRepetition(1)
                                .setRec(secToMills(10))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Sit ups")
                                .setReps(10)
                                .setRepetition(1)
                                .setRec(secToMills(10))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Nancy")
                        .setCategory(Workout.WorkoutCategory.FUNCTIONALTRAINING)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .addMuscleGroup(Workout.MuscleGroup.CARDIO)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Warm up")
                                .setReps(((int) secToMills(600)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("400mt run")
                                .setReps(400)
                                .setRepetition(10)
                                .setRec(secToMills(30))
                                .setIsReps(true)
                                .setSupersetExercise(15, true, "Squats")
                                .build())
                        .build()
        );

        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Kalsu")
                        .setCategory(Workout.WorkoutCategory.FUNCTIONALTRAINING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.CARDIO)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Dumbbell thrusters")
                                .setReps(100)
                                .setRepetition(1)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EMOM)
                                .setName("5 Burpees")
                                .setReps( (int) secToMills(60))
                                .setRepetition(10)
                                .setIsReps(false)
                                .build())
                        .build()
        );

        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Loredo")
                        .setCategory(Workout.WorkoutCategory.FUNCTIONALTRAINING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.CARDIO)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Squats")
                                .setReps(24)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Press up")
                                .setReps(24)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Walking lunge steps")
                                .setReps(24)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("400mt Run")
                                .setReps(400)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Chelsea")
                        .setCategory(Workout.WorkoutCategory.FUNCTIONALTRAINING)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Warm up")
                                .setReps(((int) secToMills(600)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EMOM)
                                .setName("Pull ups")
                                .setReps( (int) secToMills(60))
                                .setRepetition(10)
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EMOM)
                                .setName("Press ups")
                                .setReps( (int) secToMills(60))
                                .setRepetition(10)
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EMOM)
                                .setName("Squats")
                                .setReps( (int) secToMills(60))
                                .setRepetition(10)
                                .setIsReps(false)
                                .build())
                        .build()
        );

        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Murph")
                        .setCategory(Workout.WorkoutCategory.FREEBODY)
                        .setLevel(Workout.WorkoutLevel.ADVANCED)
                        .addMuscleGroup(Workout.MuscleGroup.CARDIO)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("1 Mile rune")
                                .setReps(1)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Pull ups")
                                .setReps(100)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Push ups")
                                .setReps(200)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Squats")
                                .setReps(300)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("1 Mile run")
                                .setReps(1)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        10 allenamenti fino a qui
         */

        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Gunny")
                        .setCategory(Workout.WorkoutCategory.FUNCTIONALTRAINING)
                        .setLevel(Workout.WorkoutLevel.ADVANCED)
                        .setPremium()
                        .addMuscleGroup(Workout.MuscleGroup.CARDIO)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("1 Mile weighted run")
                                .setReps(1)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Push ups")
                                .setReps(50)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Sit ups")
                                .setReps(50)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("1 Mile weighted run")
                                .setReps(1)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Push ups")
                                .setReps(50)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Sit ups")
                                .setReps(50)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("1 Mile weighted run")
                                .setReps(1)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Home chipper")
                        .setCategory(Workout.WorkoutCategory.FUNCTIONALTRAINING)
                        .setLevel(Workout.WorkoutLevel.ADVANCED)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.CARDIO)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Squats")
                                .setReps(100)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Sit ups")
                                .setReps(90)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Lunges")
                                .setReps(80)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Burpees")
                                .setReps(70)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Plank")
                                .setReps(((int) secToMills(60)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Mountain climbers")
                                .setReps(50)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Press ups")
                                .setReps(40)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Hollow rocks")
                                .setReps(40)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Jump squats")
                                .setReps(20)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Push ups")
                                .setReps(10)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Kettlebell workout")
                        .setCategory(Workout.WorkoutCategory.FUNCTIONALTRAINING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Deadlift")
                                .setReps(20)
                                .setRepetition(3)
                                .setRec(secToMills(45))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Goblet squats")
                                .setReps(20)
                                .setRepetition(3)
                                .setRec(secToMills(45))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Kettlebell swings")
                                .setReps(20)
                                .setRepetition(3)
                                .setRec(secToMills(45))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Russian twist")
                                .setReps(20)
                                .setRepetition(3)
                                .setRec(secToMills(45))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Single arm push press")
                                .setReps(20)
                                .setRepetition(3)
                                .setRec(secToMills(45))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Single arm rows")
                                .setReps(20)
                                .setRepetition(3)
                                .setRec(secToMills(45))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        #14
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Go for a run")
                        .setCategory(Workout.WorkoutCategory.FUNCTIONALTRAINING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .addMuscleGroup(Workout.MuscleGroup.CARDIO)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Run")
                                .setReps(((int) secToMills(600)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Air squats")
                                .setReps(50)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Bicycle crunches")
                                .setReps(40)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Lunges")
                                .setReps(30)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Push ups")
                                .setReps(20)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Lunge burpees")
                                .setReps(10)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        #15
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("As many burpees as possible")
                        .setCategory(Workout.WorkoutCategory.FUNCTIONALTRAINING)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.CARDIO)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Burpees")
                                .setReps(((int) secToMills(420)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .build()
        );

        /*
        #16
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("As soon as possible")
                        .setCategory(Workout.WorkoutCategory.FUNCTIONALTRAINING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .setPremium()
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.CARDIO)
                        .addMuscleGroup(Workout.MuscleGroup.CALVES)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Step ups")
                                .setReps(1000)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        #17
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Bounce")
                        .setCategory(Workout.WorkoutCategory.FUNCTIONALTRAINING)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.CALVES)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.CARDIO)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("Burpees")
                                .setReps(10)
                                .setRepetition(5)
                                .setRec(secToMills(30))
                                .setIsReps(true)
                                .setSupersetExercise(400, true, "400mt Run")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Triceps dips")
                                .setReps(15)
                                .setRepetition(5)
                                .setRec(secToMills(30))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        #18
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Running and strengthening")
                        .setCategory(Workout.WorkoutCategory.FUNCTIONALTRAINING)
                        .setLevel(Workout.WorkoutLevel.ADVANCED)
                        .addMuscleGroup(Workout.MuscleGroup.CARDIO)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("200mt Run")
                                .setReps(200)
                                .setRepetition(10)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .setSupersetExercise(10, true, "Push ups")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.REST)
                                .setRec(secToMills(120))
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("200mt Run")
                                .setReps(200)
                                .setRepetition(8)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .setSupersetExercise(15, true, "Squat thrusts")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.REST)
                                .setRec(secToMills(120))
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("200mt Run")
                                .setReps(200)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .setSupersetExercise(10, true, "Military press")
                                .build())
                        .build()
        );

        /*
        #19
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("15 minute workout")
                        .setCategory(Workout.WorkoutCategory.FUNCTIONALTRAINING)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.FEMORAL_BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.CARDIO)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.TABATA)
                                .setName("Lateral jump")
                                .setReps((int) secToMills(40))
                                .setRepetition(5)
                                .setRec(secToMills(20))
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.TABATA)
                                .setName("Reverse lunges")
                                .setReps((int) secToMills(40))
                                .setRepetition(5)
                                .setRec(secToMills(20))
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.TABATA)
                                .setName("Kettlebell swings")
                                .setReps((int) secToMills(40))
                                .setRepetition(5)
                                .setRec(secToMills(20))
                                .build())
                        .build()
        );

        /*
        #20
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("5x8 for beginners")
                        .setCategory(Workout.WorkoutCategory.FUNCTIONALTRAINING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .setPremium()
                        .addMuscleGroup(Workout.MuscleGroup.LUMBAR)
                        .addMuscleGroup(Workout.MuscleGroup.FEMORAL_BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Deadlifts")
                                .setReps(8)
                                .setRepetition(5)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Bent over rows")
                                .setReps(8)
                                .setRepetition(5)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("Overhead presses")
                                .setReps(8)
                                .setRepetition(5)
                                .setRec(secToMills(60))
                                .setIsReps(true)
                                .setSupersetExercise(8, true, "Strinct presses")
                                .build())
                        .build()
        );


    }
}
