package com.italianswapp.yourtraining.WorkoutProposed.WorkoutProposed;

import com.italianswapp.yourtraining.Timer.Circuit.CircuitSettings.Exercise;
import com.italianswapp.yourtraining.Timer.Circuit.CircuitSettings.ExerciseBuilder;
import com.italianswapp.yourtraining.WorkoutProposed.Workout.Workout;
import com.italianswapp.yourtraining.WorkoutProposed.Workout.WorkoutBuilder;

public class StretchingWorkoutProposed extends  ProposedWorkoutList {

    public StretchingWorkoutProposed() {
        super();
        initializeWorkoutList();
    }

    private void initializeWorkoutList() {
        /*
        #1
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Universal warmup")
                        .setCategory(Workout.WorkoutCategory.STRETCHING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .setPremium()
                        .addMuscleGroup(Workout.MuscleGroup.CARDIO)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.LUMBAR)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Hop on the spot")
                                .setReps(30)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Side to side hops")
                                .setReps(30)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Hip rotations")
                                .setReps(30)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Chest expansions")
                                .setReps(30)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Alt chest exspansions")
                                .setReps(30)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Raised arm circles")
                                .setReps(30)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        #2
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Rest and repair")
                        .setCategory(Workout.WorkoutCategory.STRETCHING)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.LUMBAR)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Side leg raises")
                                .setReps(40)
                                .setRepetition(3)
                                .setRec(secToMills(30))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Backward leg raises")
                                .setReps(40)
                                .setRepetition(3)
                                .setRec(secToMills(30))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Glute flex")
                                .setReps(10)
                                .setRepetition(2)
                                .setRec(secToMills(30))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Half wipers")
                                .setReps(10)
                                .setRepetition(2)
                                .setRec(secToMills(30))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Clamshells")
                                .setReps(10)
                                .setRepetition(2)
                                .setRec(secToMills(30))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        #3
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Recovery workout")
                        .setCategory(Workout.WorkoutCategory.STRETCHING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.LUMBAR)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Low side leg raised")
                                .setReps(30)
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Hip rotations")
                                .setReps(6)
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Straight leg back swings")
                                .setReps(30)
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Hip rotations")
                                .setReps(6)
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.REST)
                                .setRec(secToMills(60))
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Back and forth tilts")
                                .setReps(6)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Side to side tilts")
                                .setReps(6)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Neck rotations")
                                .setReps(6)
                                .setRepetition(3)
                                .setRec(secToMills(20))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        #4
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Hero stretch")
                        .setCategory(Workout.WorkoutCategory.STRETCHING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .setPremium()
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.FEMORAL_BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addMuscleGroup(Workout.MuscleGroup.DELTOIDS)
                        .addMuscleGroup(Workout.MuscleGroup.CHEST)
                        .addMuscleGroup(Workout.MuscleGroup.LUMBAR)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Side to side lunges")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Plank step-ins")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Shoulder stretch")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Lumbar stretch")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Femoral biceps stretch")
                                .setReps(((int) secToMills(60)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Upward downward dog")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Swimmers")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Bow hold")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .build()
        );

        /*
        #5
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Lowerbody stretch")
                        .setCategory(Workout.WorkoutCategory.STRETCHING)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.FEMORAL_BICEPS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Leg extensions")
                                .setReps(((int) secToMills(20)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("Raised leg swings")
                                .setReps(20)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .setSupersetExercise(20, false, "Raised leg hold")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Leg raises")
                                .setReps(((int) secToMills(20)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("Raised leg circles")
                                .setReps(20)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .setSupersetExercise(20, false, "Raised leg hold")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Side leg raises")
                                .setReps(((int) secToMills(20)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("Raised leg kicks")
                                .setReps(20)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .setSupersetExercise(20, false, "Raised leg hold")
                                .build())
                        .build()
        );

        /*
        #6
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Goodmorning workout")
                        .setCategory(Workout.WorkoutCategory.STRETCHING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .addMuscleGroup(Workout.MuscleGroup.NECK)
                        .addMuscleGroup(Workout.MuscleGroup.SHOULDER)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.LUMBAR)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.FEET)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Side-to-side turns")
                                .setReps(4)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Neck stretch")
                                .setReps(2)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Side-to-side tilts")
                                .setReps(4)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Shoulders rotations")
                                .setReps(4)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Straght back hold")
                                .setReps(((int) secToMills(10)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Shoulder back hold")
                                .setReps(((int) secToMills(10)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Half twist hold")
                                .setReps(((int) secToMills(5)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Overhead stretch hold")
                                .setReps(((int) secToMills(5)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Knee raise hold")
                                .setReps(((int) secToMills(10)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Calf raises")
                                .setReps(4)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Toe curls")
                                .setReps(4)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Side tilts")
                                .setReps(4)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(true)
                                .build())
                        .build()
        );

        /*
        #7
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Ease-out")
                        .setCategory(Workout.WorkoutCategory.STRETCHING)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.FEMORAL_BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.DORSALS)
                        .addMuscleGroup(Workout.MuscleGroup.LUMBAR)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Side leg raises")
                                .setReps(((int) secToMills(60)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Lunge stretches")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Side-to-side lunges")
                                .setReps(((int) secToMills(10)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("Leg raises")
                                .setReps(60)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .setSupersetExercise(30, false, "Leg raises hold")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Downward upward dog")
                                .setReps(((int) secToMills(10)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.SUPERSET)
                                .setName("Raised leg swings")
                                .setReps(60)
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .setSupersetExercise(30, false, "Raised leg swing hold")
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Back extensions")
                                .setReps(((int) secToMills(10)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())

                        .build()
        );

        /*
        #8
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("After run stretch")
                        .setPremium()
                        .setCategory(Workout.WorkoutCategory.STRETCHING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .addMuscleGroup(Workout.MuscleGroup.CALVES)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.FEMORAL_BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Hip flexor stretch")
                                .setReps(((int) secToMills(15)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Thigh stretch")
                                .setReps(((int) secToMills(15)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Hamstring stretch")
                                .setReps(((int) secToMills(15)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Iliotibial band stretch")
                                .setReps(((int) secToMills(15)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Calf stretch")
                                .setReps(((int) secToMills(15)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Lower back stretch")
                                .setReps(((int) secToMills(15)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Buttock stretch")
                                .setReps(((int) secToMills(15)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .build()
        );

        /*
        #9
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("After run stretch 2")
                        .setCategory(Workout.WorkoutCategory.STRETCHING)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.FEMORAL_BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.CALVES)
                        .addMuscleGroup(Workout.MuscleGroup.LUMBAR)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Kneeling hip-flexor")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Hamstring stretch")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Buttock strethc")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Lower-back stretch")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Child's pose")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .build()
        );

        /*
        #10
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Essential stretch for runners")
                        .setCategory(Workout.WorkoutCategory.STRETCHING)
                        .setLevel(Workout.WorkoutLevel.BEGINNER)
                        .addMuscleGroup(Workout.MuscleGroup.QUADRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.FEMORAL_BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.CALVES)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.LUMBAR)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Quadriceps")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Hamstrings")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Calf")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Iliotibial band")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Psoas")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Gluteal muscles")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Groin")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Spine stretch")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .build()
        );

        /*
        #11
         */
        workoutList.add(
                WorkoutBuilder.newBuilder()
                        .setTitle("Daily routine")
                        .setPremium()
                        .setCategory(Workout.WorkoutCategory.STRETCHING)
                        .setLevel(Workout.WorkoutLevel.INTERMEDIATE)
                        .addMuscleGroup(Workout.MuscleGroup.BUTTOCKS)
                        .addMuscleGroup(Workout.MuscleGroup.LUMBAR)
                        .addMuscleGroup(Workout.MuscleGroup.FEMORAL_BICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.ABS)
                        .addMuscleGroup(Workout.MuscleGroup.TRICEPS)
                        .addMuscleGroup(Workout.MuscleGroup.SHOULDER)
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Lying hamstring stretch")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Ankle to knee")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Lying torso twist")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Downward dog")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Cobra")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Runner’s lunge")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Pigeon")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Shoulder stretch")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Triceps stretch")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(2)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Forward bend")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .addExercise(ExerciseBuilder.newBuilder()
                                .setType(Exercise.CircuitType.EXERCISE)
                                .setName("Child’s pose")
                                .setReps(((int) secToMills(30)))
                                .setRepetition(1)
                                .setRec(secToMills(0))
                                .setIsReps(false)
                                .build())
                        .build()
        );

    }
}
